apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres_ds
    type: postgres
    access: proxy
    url: postgres:5432
    database: sec_rag
    user: postgres
    isDefault: true
    editable: true
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
