apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres_ds
    type: postgres
    access: proxy
    url: postgres:5432
    database: $__env{POSTGRES_DB}
    user: $__env{POSTGRES_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
